//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Internal.MSContactImporter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Mailbox {
            get {
                return ((string)(this["Mailbox"]));
            }
            set {
                this["Mailbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<RootMSFTees><RootMSFTee logon=\"cdebilbao\" recurseLevel=\"-1\" /></RootMSFTees>")]
        public string RootMSFTees {
            get {
                return ((string)(this["RootMSFTees"]));
            }
            set {
                this["RootMSFTees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GC://europe.corp.microsoft.com")]
        public string RootDirectoryEntry {
            get {
                return ((string)(this["RootDirectoryEntry"]));
            }
            set {
                this["RootDirectoryEntry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GC://europe.corp.microsoft.com/{0}")]
        public string DistinguishedNameFormat {
            get {
                return ((string)(this["DistinguishedNameFormat"]));
            }
            set {
                this["DistinguishedNameFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Staff v2")]
        public string Categories {
            get {
                return ((string)(this["Categories"]));
            }
            set {
                this["Categories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MsStaffId")]
        public string MsStaffId {
            get {
                return ((string)(this["MsStaffId"]));
            }
            set {
                this["MsStaffId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://schemas.microsoft.com/mapi/string/{00020329-0000-0000-C000-000000000046}/")]
        public string ExtendedPropertySchema {
            get {
                return ((string)(this["ExtendedPropertySchema"]));
            }
            set {
                this["ExtendedPropertySchema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportPhotos {
            get {
                return ((bool)(this["ImportPhotos"]));
            }
            set {
                this["ImportPhotos"] = value;
            }
        }
    }
}
