name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: src
      run: msbuild Microsoft.Internal.MSContactImporter/Microsoft.Internal.MSContactImporter.csproj
      
