name: CI Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: restore nuget
      run: nuget restore src/Microsoft.Internal.MSContactImporter.sln
      
    - name: MSBuild
      working-directory: src
      run: msbuild Microsoft.Internal.MSContactImporter.sln -p:Configuration=Release
    
    - uses: actions/upload-artifact@v1
      with:
        name: MSContactImporter
        path: src/Microsoft.Internal.MSContactImporter/bin/Release
